title: Advanced Network Design and Implementation Lab Instructions
description: Lab instructions for the Advanced Network Design and Implementation Unit
author: Xiaofei Xu and Joseph Stevens
theme: minima

header_pages:
  - index.md
  - labs/lab-0.md
  - labs/lab-1.md
  - labs/lab-2.md
  - labs/lab-3.md

show_excerpts: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
